twitch_user_ID: 
discord_webhook_URLs:
  -

embed:
  author:
    name:
      - ğŸ‰ Attention Panda Patients! ğŸ‰
      - ğŸš¨ Panda Alert! ğŸš¨
      - ğŸ¾ Paws Up, Panda Squad! ğŸ¾
      - ğŸ® Panda Party Alert! ğŸ‰
      - ğŸŒŸ Attention Patients! ğŸ¾
      - ğŸ® Panda Clinic Now Open! ğŸ¥ğŸ¼
      - ğŸŒŸ Welcome to the Panda Clinic! ğŸ¼ğŸ¥
      - ğŸ® Step into the Panda Clinic! ğŸ¼ğŸ¥
      - ğŸŒŸ Get Ready for Your Checkup at the Panda Clinic! ğŸ¼ğŸ¥
    url:
      -
    icon_url:
      - 

  thumbnail: "{user_pfp}"

  title:
    - "ğŸ”´ LIVE NOW:\n{title}"
  url: "{stream_url}"
  description:
    - "ğŸ¼ Guess who's live on Twitch? That's right, your favorite bamboo muncher, {user_name}! ğŸ®ğŸ¥\n\nğŸŒŸ Join the panda party as we dive into some gaming adventures and hilarity. Don't miss out on the fun! ğŸ‰\n\nTags: {tags}"
    - "ğŸ¼ Brace yourselves, fellow bamboo enthusiasts! {user_name} is live and ready to rock the gaming world! ğŸ®ğŸŒŸ\n\nğŸ‰ Swing by the stream for some pandemonium and laughter. It's going to be a bamboo-tiful time! ğŸ‰ğŸ¾\n\nTags: {tags}"
    - "ğŸŒŸ It's that time again - {user_name} is LIVE and kicking off an epic gaming journey! Get ready to join the panda patients! ğŸ‰ğŸ¼\n\nğŸ”¥ Dive into the stream for endless laughs, epic fails, and unbe-leaf-able moments! ğŸƒğŸ®\n\nTags: {tags}"
    - "ğŸ¼ Hey there, panda patients! The gaming clinic is open, and {user_name} is leading the charge in \"{game_name}\"! ğŸ®ğŸŒŸ\n\nğŸ‰ Swing by the stream for some epic gameplay and panda-tastic time. Let's turn this into a bamboo bash to remember! ğŸ¾ğŸ‰\n\nTags: {tags}"
    - "ğŸ® Get your game faces on because {user_name} is live and ready to rumble in \"{game_name}\"! It's time to unleash the panda power! ğŸ¼ğŸ’¥\n\nğŸ‰ Join us for a wild ride filled with gaming adventures and enough panda puns to make you groan! ğŸ®ğŸŒŸ\n\nTags: {tags}"
    - "ğŸ¾ Attention, lovely visitors! Dr. {user_name} is in the house, ready to diagnose your gaming needs and prescribe some serious fun in \"{game_name}\"! ğŸ®ğŸŒŸ\n\nğŸ©º Step into our virtual clinic for a checkup of laughter, healing gameplay, and a dose of panda-tastic entertainment. Let's cure those boredom blues together! ğŸ¼ğŸ’Š\n\nTags: {tags}"
    - "ğŸ® Prepare for a consultation like no other! Dr. {user_name} is here to treat your gaming woes with a healthy dose of \"{game_name}\" fun! ğŸ©ºğŸ’¥\n\nğŸ‰ Join our bustling clinic for an unforgettable session of gameplay, laughter, and panda puns galore. Your prescription for a great time starts now! ğŸ®ğŸŒŸ\n\nTags: {tags}"
    - "ğŸ¾ Welcome, dear visitors, to the Panda Clinic, where Dr. {user_name} is on duty to cure your gaming blues with a healthy dose of \"{game_name}\"! ğŸ®ğŸŒŸ\n\nğŸ’¼ Our clinic is open for gaming consultations, laughter therapy, and a prescription of pure panda joy. Let's embark on a healing journey together! ğŸ©ºğŸ¾\n\nTags: {tags}"
    - "ğŸ® Ready for your gaming checkup? Dr. {user_name} is here to ensure your dose of \"{game_name}\" is just what the doctor ordered! ğŸ©ºğŸ’¥\n\nğŸ‰ Join us in the Panda Clinic for a session of gaming therapy, laughter, and a panda's touch of magic. Your cure for boredom is just a stream away! ğŸ®ğŸŒŸ\n\nTags: {tags}"
    - "ğŸ¾ Calling all gaming patients! Dr. {user_name} is here to administer the perfect remedy for your gaming needs in \"{game_name}\"! ğŸ®ğŸŒŸ\n\nğŸ’¼ Step into our cozy clinic for a dose of laughter, excitement, and a touch of panda charm. Let's embark on a gaming adventure together! ğŸ©ºğŸ¾\n\nTags: {tags}"
    - "ğŸ® Dr. {user_name} is in the house and ready to diagnose your gaming cravings with a healthy dose of \"{game_name}\" excitement! ğŸ©ºğŸ’¥\n\nğŸ‰ Join us in the Panda Clinic for a session of gaming therapy, panda puns, and unforgettable moments.  ğŸ®ğŸŒŸ\n\nTags: {tags}"
  
  image: "{thumbnail_url}"

  color: 0x6441a5

  footer:
    text:
      - ğŸšª The clinic doors are open - come on in and let's start the treatment! ğŸ¾ğŸ®
      - ğŸ’Š Your gaming prescription awaits - don't keep the doctor waiting! ğŸ¼ğŸ®
      - ğŸ’¼ The clinic doors are open - step right in and let's make today's session one to remember! ğŸ¾ğŸ®
      - ğŸšª Don't keep the doctor waiting - come on in and let's make some memories! ğŸ¼ğŸ®
      - ğŸ’Š Pandas, unite! Let's heal the world, one game at a time! See you in the clinic! ğŸ¾ğŸ®
      - ğŸš‘ Don't miss your appointment with joy - hurry in and let's make some gaming miracles happen! ğŸ¾ğŸ‰
      - ğŸƒ Let's create some bamboo-tiful memories together! See you in the stream! ğŸ¼ğŸ®
      - ğŸ¼ Don't be bamboo-zled by missing out - hop in and join the fun! ğŸ®ğŸ‰
      - ğŸƒ Let's create some bamboo-tiful memories together! See you in the stream! ğŸ¼ğŸ®
      - ğŸ¼ Don't be bamboo-zled by missing out - hop in and join the fun! ğŸ®ğŸ‰
      - ğŸ‰ Pandas unite! Let's make this stream one for the bamboo history books! ğŸ¼ğŸ®
      - ğŸ® Panda power activate! Let's show 'em how it's done! ğŸ¼ğŸ’¥
      - ğŸ¾ Get ready for some panda-tastic entertainment! Let's roll! ğŸ¼ğŸ®
    icon_url:
      -
    